version: '3'

tasks:
  lint:
    cmds:
      - hadolint Dockerfile
      - hadolint .devcontainer/Dockerfile
      - task lint:dprint
  lint:dprint:
    cmds:
      - dprint check
  fmt:
    cmds:
      - dprint fmt
