name: lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Run lint
        run: task lint:dprint
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: .devcontainer/Dockerfile
