name: tasks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: "**/Dockerfile"
      - uses: dprint/check@v2.2
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Run lint
        run: task lint:dprint
