name: tasks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian
    steps:
      - uses: actions/checkout@v4
      - name: Install dprint
        uses: dprint/check@v2.2
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Run lint
        run: task lint
