name: tasks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
      - uses: dprint/check@v2.2
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Run lint
        run: task lint:dprint
